name: Keep Supabase Alive

on:
  schedule:
    # Berjalan setiap 4 hari sekali jam 00:00 UTC
    - cron: '0 0 */4 * *'
  workflow_dispatch: # Tombol rahasia biar bisa Anda tes jalanin manual di GitHub

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Ping Supabase API
        run: curl -X GET "https://lwcrfvmuisptueejmbmg.supabase.co/rest/v1/dummy?select=*" -H "apikey: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3Y3Jmdm11aXNwdHVlZWptYm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyNjY5ODYsImV4cCI6MjA5NTg0Mjk4Nn0.QtlddMwZIzdlEUqouAKXTi90edqFWIkLxCnljfGSrmc" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx3Y3Jmdm11aXNwdHVlZWptYm1nIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODAyNjY5ODYsImV4cCI6MjA5NTg0Mjk4Nn0.QtlddMwZIzdlEUqouAKXTi90edqFWIkLxCnljfGSrmc"